services:
  - type: web
    name: shoply-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://shoply-backend-d9gk.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html